### ISSUE TITLE
Compiler overriding

### ISSUE THREAD

**Issue by l4l** [hyperledger/iroha-ed25519#8]
For now cmake overrides the system-defined compiler, would be nice to fix that

**Comment by Warchant** [comment]
Please  describe this issue more. I don't see any code that changes derived compiler.

**Comment by l4l** [comment]
Hmm you are right, that seems to be an issue in [iroha](https://github.com/hyperledger/iroha) itself
Quite messed up with the naming when I was trying to compile with mingw, it still produces the `libed25519.so.1.3.00` file, instead of `ed25519.dll` or smth like that. Although it is dll inside as intended
